[package]
name = "tcp-listener-tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3.0"
env_logger = "0.10.0"
fastrand = "1.8.0"
log = "0.4.17"
speedy = "0.8.5"
tokio = { version = "1", features = ["full"] }
